export { default as GraphQLActorAPI } from './queries'
// export { default as Mutation } from './mutations'
export { GraphQLActor, GraphQLActorConnection } from './schema'
export { default as Actor } from './model'
export { default as Loader } from './loaders'
